/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package expeditors.backend.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FullAdopterMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6872092311891973295L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FullAdopterMessage\",\"namespace\":\"expeditors.backend.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of Adopter\",\"default\":\"\"},{\"name\":\"phoneNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Phone Number\",\"default\":\"\"},{\"name\":\"adoptionDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Date the pet was adopted\",\"default\":\"\"},{\"name\":\"pets\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroPet\",\"fields\":[{\"name\":\"pet_type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Type of Animal\"},{\"name\":\"pet_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Pet Name, if known\",\"default\":\"\"},{\"name\":\"pet_breed\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Pet Breed, if known (e.g. siamese, dalmation)\",\"default\":\"\"},{\"name\":\"adoption_date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Date of adoption, if known\",\"default\":\"\"}]}}},{\"name\":\"time_stamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Datetime when the message was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FullAdopterMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FullAdopterMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FullAdopterMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FullAdopterMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FullAdopterMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FullAdopterMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FullAdopterMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FullAdopterMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FullAdopterMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of Adopter */
  private java.lang.String name;
  /** Phone Number */
  private java.lang.String phoneNumber;
  /** Date the pet was adopted */
  private java.lang.String adoptionDate;
  private java.util.List<expeditors.backend.avro.AvroPet> pets;
  /** Datetime when the message was generated */
  private java.lang.String time_stamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FullAdopterMessage() {}

  /**
   * All-args constructor.
   * @param name Name of Adopter
   * @param phoneNumber Phone Number
   * @param adoptionDate Date the pet was adopted
   * @param pets The new value for pets
   * @param time_stamp Datetime when the message was generated
   */
  public FullAdopterMessage(java.lang.String name, java.lang.String phoneNumber, java.lang.String adoptionDate, java.util.List<expeditors.backend.avro.AvroPet> pets, java.lang.String time_stamp) {
    this.name = name;
    this.phoneNumber = phoneNumber;
    this.adoptionDate = adoptionDate;
    this.pets = pets;
    this.time_stamp = time_stamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return phoneNumber;
    case 2: return adoptionDate;
    case 3: return pets;
    case 4: return time_stamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: phoneNumber = value$ != null ? value$.toString() : null; break;
    case 2: adoptionDate = value$ != null ? value$.toString() : null; break;
    case 3: pets = (java.util.List<expeditors.backend.avro.AvroPet>)value$; break;
    case 4: time_stamp = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of Adopter
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Name of Adopter
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   * @return Phone Number
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }


  /**
   * Sets the value of the 'phoneNumber' field.
   * Phone Number
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.String value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'adoptionDate' field.
   * @return Date the pet was adopted
   */
  public java.lang.String getAdoptionDate() {
    return adoptionDate;
  }


  /**
   * Sets the value of the 'adoptionDate' field.
   * Date the pet was adopted
   * @param value the value to set.
   */
  public void setAdoptionDate(java.lang.String value) {
    this.adoptionDate = value;
  }

  /**
   * Gets the value of the 'pets' field.
   * @return The value of the 'pets' field.
   */
  public java.util.List<expeditors.backend.avro.AvroPet> getPets() {
    return pets;
  }


  /**
   * Sets the value of the 'pets' field.
   * @param value the value to set.
   */
  public void setPets(java.util.List<expeditors.backend.avro.AvroPet> value) {
    this.pets = value;
  }

  /**
   * Gets the value of the 'time_stamp' field.
   * @return Datetime when the message was generated
   */
  public java.lang.String getTimeStamp() {
    return time_stamp;
  }


  /**
   * Sets the value of the 'time_stamp' field.
   * Datetime when the message was generated
   * @param value the value to set.
   */
  public void setTimeStamp(java.lang.String value) {
    this.time_stamp = value;
  }

  /**
   * Creates a new FullAdopterMessage RecordBuilder.
   * @return A new FullAdopterMessage RecordBuilder
   */
  public static expeditors.backend.avro.FullAdopterMessage.Builder newBuilder() {
    return new expeditors.backend.avro.FullAdopterMessage.Builder();
  }

  /**
   * Creates a new FullAdopterMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FullAdopterMessage RecordBuilder
   */
  public static expeditors.backend.avro.FullAdopterMessage.Builder newBuilder(expeditors.backend.avro.FullAdopterMessage.Builder other) {
    if (other == null) {
      return new expeditors.backend.avro.FullAdopterMessage.Builder();
    } else {
      return new expeditors.backend.avro.FullAdopterMessage.Builder(other);
    }
  }

  /**
   * Creates a new FullAdopterMessage RecordBuilder by copying an existing FullAdopterMessage instance.
   * @param other The existing instance to copy.
   * @return A new FullAdopterMessage RecordBuilder
   */
  public static expeditors.backend.avro.FullAdopterMessage.Builder newBuilder(expeditors.backend.avro.FullAdopterMessage other) {
    if (other == null) {
      return new expeditors.backend.avro.FullAdopterMessage.Builder();
    } else {
      return new expeditors.backend.avro.FullAdopterMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for FullAdopterMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FullAdopterMessage>
    implements org.apache.avro.data.RecordBuilder<FullAdopterMessage> {

    /** Name of Adopter */
    private java.lang.String name;
    /** Phone Number */
    private java.lang.String phoneNumber;
    /** Date the pet was adopted */
    private java.lang.String adoptionDate;
    private java.util.List<expeditors.backend.avro.AvroPet> pets;
    /** Datetime when the message was generated */
    private java.lang.String time_stamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(expeditors.backend.avro.FullAdopterMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[1].schema(), other.phoneNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.adoptionDate)) {
        this.adoptionDate = data().deepCopy(fields()[2].schema(), other.adoptionDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.pets)) {
        this.pets = data().deepCopy(fields()[3].schema(), other.pets);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.time_stamp)) {
        this.time_stamp = data().deepCopy(fields()[4].schema(), other.time_stamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing FullAdopterMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(expeditors.backend.avro.FullAdopterMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[1].schema(), other.phoneNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.adoptionDate)) {
        this.adoptionDate = data().deepCopy(fields()[2].schema(), other.adoptionDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pets)) {
        this.pets = data().deepCopy(fields()[3].schema(), other.pets);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.time_stamp)) {
        this.time_stamp = data().deepCopy(fields()[4].schema(), other.time_stamp);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * Name of Adopter
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Name of Adopter
      * @param value The value of 'name'.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of Adopter
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of Adopter
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneNumber' field.
      * Phone Number
      * @return The value.
      */
    public java.lang.String getPhoneNumber() {
      return phoneNumber;
    }


    /**
      * Sets the value of the 'phoneNumber' field.
      * Phone Number
      * @param value The value of 'phoneNumber'.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder setPhoneNumber(java.lang.String value) {
      validate(fields()[1], value);
      this.phoneNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumber' field has been set.
      * Phone Number
      * @return True if the 'phoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'phoneNumber' field.
      * Phone Number
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'adoptionDate' field.
      * Date the pet was adopted
      * @return The value.
      */
    public java.lang.String getAdoptionDate() {
      return adoptionDate;
    }


    /**
      * Sets the value of the 'adoptionDate' field.
      * Date the pet was adopted
      * @param value The value of 'adoptionDate'.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder setAdoptionDate(java.lang.String value) {
      validate(fields()[2], value);
      this.adoptionDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'adoptionDate' field has been set.
      * Date the pet was adopted
      * @return True if the 'adoptionDate' field has been set, false otherwise.
      */
    public boolean hasAdoptionDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'adoptionDate' field.
      * Date the pet was adopted
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder clearAdoptionDate() {
      adoptionDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'pets' field.
      * @return The value.
      */
    public java.util.List<expeditors.backend.avro.AvroPet> getPets() {
      return pets;
    }


    /**
      * Sets the value of the 'pets' field.
      * @param value The value of 'pets'.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder setPets(java.util.List<expeditors.backend.avro.AvroPet> value) {
      validate(fields()[3], value);
      this.pets = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'pets' field has been set.
      * @return True if the 'pets' field has been set, false otherwise.
      */
    public boolean hasPets() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'pets' field.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder clearPets() {
      pets = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'time_stamp' field.
      * Datetime when the message was generated
      * @return The value.
      */
    public java.lang.String getTimeStamp() {
      return time_stamp;
    }


    /**
      * Sets the value of the 'time_stamp' field.
      * Datetime when the message was generated
      * @param value The value of 'time_stamp'.
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder setTimeStamp(java.lang.String value) {
      validate(fields()[4], value);
      this.time_stamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'time_stamp' field has been set.
      * Datetime when the message was generated
      * @return True if the 'time_stamp' field has been set, false otherwise.
      */
    public boolean hasTimeStamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'time_stamp' field.
      * Datetime when the message was generated
      * @return This builder.
      */
    public expeditors.backend.avro.FullAdopterMessage.Builder clearTimeStamp() {
      time_stamp = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FullAdopterMessage build() {
      try {
        FullAdopterMessage record = new FullAdopterMessage();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.phoneNumber = fieldSetFlags()[1] ? this.phoneNumber : (java.lang.String) defaultValue(fields()[1]);
        record.adoptionDate = fieldSetFlags()[2] ? this.adoptionDate : (java.lang.String) defaultValue(fields()[2]);
        record.pets = fieldSetFlags()[3] ? this.pets : (java.util.List<expeditors.backend.avro.AvroPet>) defaultValue(fields()[3]);
        record.time_stamp = fieldSetFlags()[4] ? this.time_stamp : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FullAdopterMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<FullAdopterMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FullAdopterMessage>
    READER$ = (org.apache.avro.io.DatumReader<FullAdopterMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.phoneNumber);

    out.writeString(this.adoptionDate);

    long size0 = this.pets.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (expeditors.backend.avro.AvroPet e0: this.pets) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.time_stamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString();

      this.phoneNumber = in.readString();

      this.adoptionDate = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<expeditors.backend.avro.AvroPet> a0 = this.pets;
      if (a0 == null) {
        a0 = new SpecificData.Array<expeditors.backend.avro.AvroPet>((int)size0, SCHEMA$.getField("pets").schema());
        this.pets = a0;
      } else a0.clear();
      SpecificData.Array<expeditors.backend.avro.AvroPet> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<expeditors.backend.avro.AvroPet>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          expeditors.backend.avro.AvroPet e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new expeditors.backend.avro.AvroPet();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.time_stamp = in.readString();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString();
          break;

        case 1:
          this.phoneNumber = in.readString();
          break;

        case 2:
          this.adoptionDate = in.readString();
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<expeditors.backend.avro.AvroPet> a0 = this.pets;
          if (a0 == null) {
            a0 = new SpecificData.Array<expeditors.backend.avro.AvroPet>((int)size0, SCHEMA$.getField("pets").schema());
            this.pets = a0;
          } else a0.clear();
          SpecificData.Array<expeditors.backend.avro.AvroPet> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<expeditors.backend.avro.AvroPet>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              expeditors.backend.avro.AvroPet e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new expeditors.backend.avro.AvroPet();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 4:
          this.time_stamp = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










