
DROP TABLE PHONENUMBER IF EXISTS;
DROP TABLE CUSTOMER IF EXISTS;

CREATE USER IF NOT EXISTS LARKU SALT 'f2d97d5e5c194fe4' HASH 'bf9ac7082b79123183a1a58f3f23b3822cbedc5c1161394f43bd4d0d03237c59' ADMIN;

CREATE MEMORY TABLE CUSTOMER(
    ID INTEGER primary key auto_increment not null,
    NAME VARCHAR(255),
    DOB DATE,
    STATUS VARCHAR(255)
);

CREATE MEMORY TABLE PHONENUMBER(
    ID INTEGER primary key auto_increment not null,
    PHONENUMBER VARCHAR(255),
    TYPE VARCHAR(10),
    CUSTOMER_ID INTEGER
);


ALTER TABLE PHONENUMBER ADD CONSTRAINT PUBLIC.PHONENUMBER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID); -- NOCHECK;
ALTER TABLE PHONENUMBER ADD CONSTRAINT PUBLIC.PHONENUMBER_TO_CUSTOMER UNIQUE(PHONENUMBER, CUSTOMER_ID);
--index etc.
