-- Tracker Schema generated by Postgres

drop table if exists public.track_artist;
drop table if exists public.artist;
drop table if exists public.track;

create table if not exists public.artist
(
    artist_id serial primary key,
    discogs_id varchar(255)
    constraint artist_discogs_id_unique
        unique,
    name       varchar(255),
    profile    varchar(10000),
    real_name  varchar(255)
);

alter table public.artist owner to larku;

create table if not exists public.track
(
    track_id serial primary key,
    album        varchar(255),
    duration     bigint,
    format       varchar(255),
    genre       varchar(255),
    release_year varchar(255),
    title        varchar(255)
);

alter table public.track owner to larku;

create table if not exists public.track_artist
(
    track_id    integer not null
    constraint fkp3qpu7m4npqt5q8byutno5bvm references public.track,

    artist_id integer not null
        constraint fk76nfjalp4aok5hlajhmsunrcf references public.artist,
    primary key (track_id, artist_id)
    );

alter table public.track_artist owner to larku;
